### ISSUE TITLE
event.blockingParticipate() issue

### ISSUE THREAD

**Issue by Valodya89** [MySocialApp/mysocialapp-swift-client#1]
We have trying to use following scenario when user going to join an event
The event.blockingParticipate() trown an error ( please see attachment )
Could you please clarify and help to figure out possible soultions?
1. If we need to use another requests what will be an example of code.
2. if we need to use same method could it possible some restriction from server side or the code sample is not fully provided.
We have using
Swift version 4.1
Xcode 9.3.1
![screen shot 2018-06-07 at 3 54 02 pm](https://user-images.githubusercontent.com/9318170/41147263-00d5068a-6b17-11e8-876a-f8f24061e9f5.png)
 Regards

**Comment by Gobountz** [comment]
Hi,

To help you handle exceptions while calling actions on elements, you can catch the "RestError" thrown by the methods :
- be sure to use the latest version of the SDK (currently the 1.0.10)
- call the action as follow :
```swift
do {
  try event.blockingParticipate()
} catch let error {
  if let e = error as? RestError {
    e.exception // must be io.mysocialapp.module.event.services.NotValidActionException in your case
    e.message // must be "This action is not valid"
  }
}
```

Exceptions on calls to participate() are mainly caused by incompatibility between the Event (date, owner, access rights) and the current User.

Are you sure that the Event you are trying to join is still in the future ? Is there still any seat left ?

**Comment by Valodya89** [comment]
@Gobountz  we have upgraded new version to 1.0.10 and made test from events that have start dates in the future
and it works.
Thank you for support
